import React from 'react';

export const NAMES =[
    {label:"Human",value:1},
    {label: 'bicycle', value : 2},
    {label: 'car', value: 3},
    {label: 'motorbike', value: 4},
    {label: 'aeroplane', value: 5},
    {label: 'bus', value: 6},
    {label: 'train', value: 7},
    {label: 'truck', value: 8},
    {label: 'boat', value: 9},
    {label: 'traffic light', value: 10},
    {label: 'fire hydrant', value: 11},
    {label: 'stop sign', value: 12},
    {label: 'parking meter', value: 13},
    {label: 'bench', value: 14},
    {label: 'bird', value: 15},
    {label: 'cat', value: 16},
    {label: 'dog', value: 17},
    {label: 'horse', value: 18},
    {label: 'sheep', value: 19},
    {label: 'cow', value: 20},
    {label: 'elephant', value: 21},
    {label: 'bear', value: 22},
    {label: 'zebra', value: 23},
    {label: 'giraffe', value: 24},
    {label: 'backpack', value: 25},
    {label: 'umbrella', value: 26},
    {label: 'handbag', value: 27},
    {label: 'tie', value: 28},
    {label: 'suitcase', value: 29},
    {label: 'frisbee', value: 30},
    {label: 'skis', value: 31},
    {label: 'snowboard', value: 32},
    {label: 'sports ball', value: 33},
    {label: 'kite', value: 34},
    {label: 'baseball bat', value: 35},
    {label: 'baseball glove', value: 36},
    {label: 'skateboard', value: 37},
    {label: 'surfboard', value: 38},
    {label: 'tennis racket', value: 39},
    {label: 'bottle', value: 40},
    {label: 'wine glass', value: 41},
    {label: 'cup', value: 42},
    {label: 'fork', value: 43},
    {label: 'knife', value: 44},
    {label: 'spoon', value: 45},
    {label: 'bowl', value: 46},
    {label: 'banana', value: 47},
    {label: 'apple', value: 48},
    {label: 'sandwich', value: 49},
    {label: 'orange', value: 50},
    {label: 'broccoli', value: 51},
    {label: 'carrot', value: 52},
    {label: 'hot dog', value: 53},
    {label: 'pizza', value: 54},
    {label: 'donut', value: 55},
    {label: 'cake', value: 56},
    {label: 'chair', value: 57},
    {label: 'sofa', value: 58},
    {label: 'pottedplant', value: 59},
    {label: 'bed', value: 60},
    {label: 'diningtable', value: 61},
    {label: 'toilet', value: 62},
    {label: 'tvmonitor', value: 63},
    {label: 'laptop', value: 64},
    {label: 'mouse', value: 65},
    {label: 'remote', value: 66},
    {label: 'keyboard', value: 67},
    {label: 'cell phone', value: 68},
    {label: 'toothbrush', value: 69},
    {label: 'hair drier', value: 70},
    {label: 'teddy bear', value: 71},
    {label: 'scissors', value: 72},
    {label: 'person', value: 73},
    {label: 'vase', value: 74},
    {label: 'clock', value: 75},
    {label: 'book', value: 76},
    {label: 'refrigerator', value: 77},
    {label: 'sink', value: 78},
    {label: 'toaster', value: 79},
    {label: 'oven', value: 80},
    {label: 'microwave', value: 81},
    ];